- create arrays: np.array(x, dtype=dtype)
- identity matrix: np.eye(2)

In [4]:
import numpy as np

def arr(x, dtype=float):
    return np.array(x, dtype=dtype)

A = arr([[1, 2],
        [3, 4]])

B = arr([[5, 6],
         [7, 8]])

x = arr([[9],
         [10]])

C = arr([[1, 2, 3],
         [4, 5, 6]])

# identity matrix
I2 = np.eye(2)

print("A:\n", A, "\nshape:", A.shape)
print("B:\n", B, "\nshape:", B.shape)
print("x (column vector):\n", x, "\nshape:", x.shape)
print("C (non-square):\n", C, "\nshape:", C.shape)
print("I2 (identity):\n", I2, "\nshape:", I2.shape)

A:
 [[1. 2.]
 [3. 4.]] 
shape: (2, 2)
B:
 [[5. 6.]
 [7. 8.]] 
shape: (2, 2)
x (column vector):
 [[ 9.]
 [10.]] 
shape: (2, 1)
C (non-square):
 [[1. 2. 3.]
 [4. 5. 6.]] 
shape: (2, 3)
I2 (identity):
 [[1. 0.]
 [0. 1.]] 
shape: (2, 2)


# Basic element-wise operations
- operations where the two arrays must have the same shape
    - unless NumPy broadcasting can be applied
- NumPy performs the operation for each matching position

In [5]:
# Addition
add_AB = A + B
print("A + B =\n", add_AB)

# Subtraction
sub_AB = A - B
print("\nA - B =\n", sub_AB)

# Element-wise multiplication
elem_mul_AB = A * B
print("\nA * B (element-wise) =\n", elem_mul_AB)

# Element-wise division
elem_div_AB = A / B
print("\nA / B (element-wise) =\n", elem_div_AB)

# Check shapes match
print("\nShape of A:", A.shape, "Shape of B:", B.shape)

A + B =
 [[ 6.  8.]
 [10. 12.]]

A - B =
 [[-4. -4.]
 [-4. -4.]]

A * B (element-wise) =
 [[ 5. 12.]
 [21. 32.]]

A / B (element-wise) =
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

Shape of A: (2, 2) Shape of B: (2, 2)


## Matrix Multiplication
- A @ B
- np.matmul(A, B)
- manual calculation

In [6]:
matmul_AB = A @ B
print("A @ B (matrix multiplication) =\n", matmul_AB)

matmul_AB2 = np.matmul(A, B)
print("\nUsing np.matmul(A, B) =\n", matmul_AB2)

manual_calc = np.array([[1*5 + 2*7, 1*6 + 2*8],
                        [3*5 + 4*7, 3*6 + 4*8]])
print("\nManual calculation =\n", manual_calc)

# non-square multiplication: (2×3) @ (3×2) → (2×2)
D = np.array([[1, 2, 3],
              [4, 5, 6]])
E = np.array([[7, 8],
              [9, 10],
              [11, 12]])
print("\nD shape:", D.shape, "E shape:", E.shape)
print("D @ E =\n", D @ E)

A @ B (matrix multiplication) =
 [[19. 22.]
 [43. 50.]]

Using np.matmul(A, B) =
 [[19. 22.]
 [43. 50.]]

Manual calculation =
 [[19 22]
 [43 50]]

D shape: (2, 3) E shape: (3, 2)
D @ E =
 [[ 58  64]
 [139 154]]


## Matrix Properties
1. Transpose
- flip a matrix over its diagonal
- rows become cols and cols become rows (first row -> first col)
- A.T
- np.transpose(A)
2. Determinant
- scalar value that tells you if a matrix is invertible
    - non-zero det: invertible
    - zero det: singular
- only for square matrices
- np.linalg.det(A)
3. Rank
- number of linearly independent rows or cols
- np.linalg.matrix_rank(A)
4. Trace
- sum of the main diagonal elements
- np.trace(A)

In [7]:
# 1. Transpose
A_T = A.T
print("Transpose of A:\n", A_T)

# 2. Determinant
det_A = np.linalg.det(A)
print("\nDeterminant of A:", det_A)

# 3. Rank
rank_A = np.linalg.matrix_rank(A)
print("Rank of A:", rank_A)

# 4. Trace
trace_A = np.trace(A)
print("Trace of A:", trace_A)

# test with identity matrix
print("\nI2:\n", I2)
print("Determinant of I2:", np.linalg.det(I2))
print("Trace of I2:", np.trace(I2))

Transpose of A:
 [[1. 3.]
 [2. 4.]]

Determinant of A: -2.0000000000000004
Rank of A: 2
Trace of A: 5.0

I2:
 [[1. 0.]
 [0. 1.]]
Determinant of I2: 1.0
Trace of I2: 2.0


## Matrix Inverse and Solving Systems of Equations
1. Inverse
- $A^{-1}$
- satisfies $A \times A^{-1} = I$
- only square, invertible matrices (det != 0)
- np.linalg.inv(A)
2. Moore–Penrose pseudo-inverse
- some matrices can't be inverted
- np.linalg.pinv(A)
    - works for more cases (least-squares solution)
3. Solving Ax = b
- instead of computing $A^{-1}$ and multiplying
- np.linalg.solve(A, b)

In [8]:
# 1. Inverse of A
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

# Verify: A @ A_inv ≈ Identity
print("\nA @ A_inv ≈ I:\n", A @ A_inv)

# 2. Pseudo-inverse of a non-square matrix C
C_pinv = np.linalg.pinv(C)
print("\nPseudo-inverse of C (2x3):\n", C_pinv)

# 3. Solving Ax = b
b = np.array([[9], [10]])  # column vector
x_sol = np.linalg.solve(A, b)
print("\nSolution x to Ax = b:\n", x_sol)

# Verify: A @ x_sol ≈ b
print("\nCheck A @ x_sol:\n", A @ x_sol)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv ≈ I:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Pseudo-inverse of C (2x3):
 [[-0.94444444  0.44444444]
 [-0.11111111  0.11111111]
 [ 0.72222222 -0.22222222]]

Solution x to Ax = b:
 [[-8. ]
 [ 8.5]]

Check A @ x_sol:
 [[ 9.]
 [10.]]
