In [1]:
import numpy as np

print(np.__version__)

2.3.2


In [8]:
print("Multiply list [1, 2, 3, 4] by 2")

my_list = [1, 2, 3, 4]
print(type(my_list))
print("Python list: ", my_list * 2)

arr = np.array([1, 2, 3, 4])
print(type(arr))
print("NumPy array: ", arr * 2)

Multiply list [1, 2, 3, 4] by 2
<class 'list'>
Python list:  [1, 2, 3, 4, 1, 2, 3, 4]
<class 'numpy.ndarray'>
NumPy array:  [2 4 6 8]


### Multidimensional arrays
- arr.ndim - get number of dims

In [17]:
arr0 = np.array('A')
print(arr0.ndim, arr0)

arr1 = np.array(['A', 'B', 'C'])
print(arr1.ndim, arr1)

arr2 = np.array([['A', 'B', 'C'],
                 ['D', 'E', 'F'],
                 ['G', 'H', 'I']])
# error
# ABC
# DEF
# GH
print(arr2.ndim, arr2)

0 A
1 ['A' 'B' 'C']
2 [['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]


### Multidimensional indexing is faster than chain indexing

In [21]:
# chain indexing
print(arr2[0][0])
# multidimensional indexing
print(arr2[0, 0])
word = arr2[1, 1] + arr2[1, 2] + arr2[0, 0]
print(word)

A
A
EFA


### Slicing
- arr[start:end:step]

In [22]:
nums = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

# single rows
print(nums[1])
print(nums[-1])

[5 6 7 8]
[13 14 15 16]


In [28]:
# multiple rows
print(nums[1:3])
print(nums[1:])
# step
print(nums[0:4:2])
nums[0:4:2] == nums[::2]
# reverse step
print(nums[::-2])

[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[13 14 15 16]
 [ 5  6  7  8]]


In [32]:
# col selection
first_col = nums[:, 0]
print(first_col)
last_col = nums[:, -1]
print(last_col)

# first three cols
print(nums[:, 0:3])

[ 1  5  9 13]
[ 4  8 12 16]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [33]:
# get first two rows and first two columns (quadrant)
print(nums[0:2, 0:2])

[[1 2]
 [5 6]]


## Arithmetic

### Scalar arithmetic
- scalar - a single value

In [38]:
array = np.array([1, 2, 3])
print(array)
print("add 1", array + 1)
print("subtract 2", array - 2)
print("multiply by 3", array * 3)
print("divide by 4", array / 4)
print("power of 5", array ** 5)

[1 2 3]
add 1 [2 3 4]
subtract 2 [-1  0  1]
multiply by 3 [3 6 9]
divide by 4 [0.25 0.5  0.75]
power of 5 [  1  32 243]


### vectorized math funcs

In [40]:
# square root
print(np.sqrt(array))

[1.         1.41421356 1.73205081]


In [43]:
array = np.array([1.02, 2.04, 3.99])
print("original", array)
# rounding
print("round", np.round(array))
# floor
print("floor", np.floor(array))
# ceiling
print("ceil", np.ceil(array))

original [1.02 2.04 3.99]
round [1. 2. 4.]
floor [1. 2. 3.]
ceil [2. 3. 4.]


In [44]:
np.pi

3.141592653589793

In [45]:
radii = np.array([1, 2, 3])
# A = pi * r^2
print(np.pi * radii ** 2)

[ 3.14159265 12.56637061 28.27433388]


### element-wise arithmetic

In [48]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("arr1", arr1)
print("arr2", arr2)
print("arr1 + arr2", arr1 + arr2)
print("arr1 - arr2", arr1 - arr2)
print("arr1 * arr2", arr1 * arr2)
print("arr1 / arr2", arr1 / arr2)
print("arr1 // arr2", arr1 // arr2)
print("arr1 ** arr2", arr1 ** arr2)

arr1 [1 2 3]
arr2 [4 5 6]
arr1 + arr2 [5 7 9]
arr1 - arr2 [-3 -3 -3]
arr1 * arr2 [ 4 10 18]
arr1 / arr2 [0.25 0.4  0.5 ]
arr1 // arr2 [0 0 0]
arr1 ** arr2 [  1  32 729]


### comparison operators
- check every element

In [49]:
scores = np.array([91, 55, 100, 73, 82, 64])
print(scores == 100)
print(scores >= 60)
print(scores < 60)

[False False  True False False False]
[ True False  True  True  True  True]
[False  True False False False False]


In [50]:
print(scores)
# any score less than 60 is set to 0
scores[scores < 60] = 0
print(scores)

[ 91  55 100  73  82  64]
[ 91   0 100  73  82  64]


### Broadcasting
- allows NumPy to perform operations of arrays with different shapes
- virtually expands dims so they match the larger array's shape
    - the dims have the same size
    - OR
    - one of the dims has a size of 1
- (1, 4) * (4, 1) -> (4, 4)
- (2, 4) * (4, 1) -> error
- (4, 4) * (4, 1) -> (4, 4)
- (4, 4) * (4, 2) -> error


In [56]:
arr1 = np.array([[1, 1, 1, 1]]) # (1, 4)
# error: (2, 4)
print(arr1.shape, arr1)
arr2 = np.array([[1], [2], [3], [4]])
print(arr2.shape, arr2)
# element-wise
print("arr1 * arr2", arr1 * arr2)

(1, 4) [[1 1 1 1]]
(4, 1) [[1]
 [2]
 [3]
 [4]]
arr1 * arr2 [[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]


### aggregate functions
- summarize data
- typically return a single value

In [68]:
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])
print(array)
print("total sum", np.sum(array), array.sum())
print("sum of every col", np.sum(array, axis=0), array.sum(axis=0))
print("sum of every row", np.sum(array, axis=1), array.sum(axis=1))
print("mean", np.mean(array), array.mean())
print("min", np.min(array), array.min())
print("max", np.max(array), array.max())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
total sum 55 55
sum of every col [ 7  9 11 13 15] [ 7  9 11 13 15]
sum of every row [15 40] [15 40]
mean 5.5 5.5
min 1 1
max 10 10


### filtering
- select elements from an array that match a given condition

In [84]:
ages = np.array([[21, 17, 19, 20, 16, 30, 18, 65],
                 [39, 22, 15, 99, 18, 19, 20, 21]])
# boolean indexing
teens = ages[ages < 18]
teens2 = ages[~(ages >= 18)]
adults = ages[(ages >= 18) & (ages < 65)]
not_adults = ages[(ages < 18) | (ages >= 65)]
evens = ages[ages % 2 == 0]
odds = ages[ages % 2 != 0]
odds2 = ages[ages % 2 == 1]
print("teens", teens, teens == teens2)
print("adults", adults)
print("not adults", not_adults)
print("evens", evens)
print("odds", odds, odds == odds2)

teens [17 16 15] [ True  True  True]
adults [21 19 20 30 18 39 22 18 19 20 21]
not adults [17 16 65 15 99]
evens [20 16 30 18 22 18 20]
odds [21 17 19 65 39 15 99 19 21] [ True  True  True  True  True  True  True  True  True]


In [89]:
new = np.where(ages >= 18, ages, 0)
ages[ages < 18] = 0
print(new)
print(ages)
print(new == ages)

[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
[[21  0 19 20  0 30 18 65]
 [39 22  0 99 18 19 20 21]]
[[ True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True]]


### random numbers

In [113]:
# no parameters - random
rng = np.random.default_rng()
# seed - pseudorandom
# rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=7, size=3))
print(rng.integers(1, 100, (3, 2)))

[3 3 4]
[[ 2 32]
 [ 7 61]
 [19 10]]


In [131]:
# seed
# np.random.seed(seed=1)

# no parameters - between 0 and 1
rnd = np.random.uniform()
print(rnd)

rnd2 = np.random.uniform(2, 4, (2, 2))
print(rnd2)

0.538816734003357
[[2.83838903 3.370439  ]
 [2.4089045  3.75623487]]


In [151]:
# shuffle on rng
rng.shuffle(rnd2)
print(rnd2)

[[2.83838903 3.370439  ]
 [2.4089045  3.75623487]]


In [155]:
nums = np.array([1, 2, 3, 4, 5])
rng.choice(nums, size=2)

array([5, 5])